version: '2.2'

services:
  asmpbackend:
    restart: unless-stopped
    build:
      context: ./ASMP23
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    entrypoint: /ASMP23/wsgi-entrypoint.sh
    volumes:
      - ./ASMP23:/ASMP23/
    expose:
      - 8000
    networks:
      - mynetwork

networks:
  mynetwork:
    name: yearbook23_mynetwork