# Generated by Django 4.2.2 on 2023-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fullname", models.CharField(max_length=255)),
                ("rollno", models.CharField(max_length=9)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("aero", "Aerospace Engineering"),
                            ("cse", "Computer Science Engineering"),
                            ("ee", "Electrical Engineering"),
                            ("mech", "Mechanical Engineering"),
                            ("chem", "Chemistry"),
                            ("biosci", "Biosciences & Bioengineering"),
                            ("che", "Chemical Engineering"),
                            ("ieor", "Industrial Engineering and Operations Research"),
                            (
                                "metallurgy",
                                "Metallurgical Engineering and Material Science",
                            ),
                            ("engphy", "Engineering Physics"),
                            ("envsci", "Environmental Science & Engineering"),
                            ("energy", "Energy Science & Engineering"),
                            ("math", "Mathematics"),
                            ("civil", "Civil Engineering"),
                            ("earthsci", "Earth Sciences and Resource engineering"),
                            ("rural", "Technology for Rural Areas"),
                            ("design", "Design"),
                            ("other", "Other (If not mentioned above)"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "department_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("btech", "B.Tech"),
                            ("bs", "B.S"),
                            ("dual_degree", "Dual Degree"),
                            ("mtech", "M.Tech"),
                            ("msc", "M.Sc"),
                            ("phd", "PhD"),
                            ("other_degree", "Other Degree"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "degree_other",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("graduation_year", models.IntegerField()),
                ("contact", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=255)),
                (
                    "placementOrGrad",
                    models.CharField(
                        choices=[
                            ("placement", "Placement"),
                            ("gradmentoring", "Grad Mentoring"),
                        ],
                        max_length=255,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("experience", models.TextField()),
                (
                    "field_pref1",
                    models.CharField(
                        choices=[
                            ("it_software", "IT/Software"),
                            ("analytics", "Analytics"),
                            ("consultancy", "Consultancy"),
                            ("finance", "Finance"),
                            ("FMCG", "FMCG"),
                            ("management", "Management"),
                            ("core", "Core"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "field_pref2",
                    models.CharField(
                        choices=[
                            ("it_software", "IT/Software"),
                            ("analytics", "Analytics"),
                            ("consultancy", "Consultancy"),
                            ("finance", "Finance"),
                            ("FMCG", "FMCG"),
                            ("management", "Management"),
                            ("core", "Core"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "field_pref3",
                    models.CharField(
                        choices=[
                            ("it_software", "IT/Software"),
                            ("analytics", "Analytics"),
                            ("consultancy", "Consultancy"),
                            ("finance", "Finance"),
                            ("FMCG", "FMCG"),
                            ("management", "Management"),
                            ("core", "Core"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "university_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("aero", "Aerospace Engineering"),
                            ("cse", "Computer Science Engineering"),
                            ("ee", "Electrical Engineering"),
                            ("mech", "Mechanical Engineering"),
                            ("chem", "Chemistry"),
                            ("biosci", "Biosciences & Bioengineering"),
                            ("che", "Chemical Engineering"),
                            ("ieor", "Industrial Engineering and Operations Research"),
                            (
                                "metallurgy",
                                "Metallurgical Engineering and Material Science",
                            ),
                            ("engphy", "Engineering Physics"),
                            ("envsci", "Environmental Science & Engineering"),
                            ("energy", "Energy Science & Engineering"),
                            ("math", "Mathematics"),
                            ("civil", "Civil Engineering"),
                            ("earthsci", "Earth Sciences and Resource engineering"),
                            ("rural", "Technology for Rural Areas"),
                            ("design", "Design"),
                            ("other", "Other (If not mentioned above)"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "branch_subdivision",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("preferred_mentees", models.IntegerField(null=True)),
                ("suggestions", models.TextField(blank=True, null=True)),
                ("alumni_recommendations", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
