# Generated by Django 4.2.2 on 2023-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0002_remove_registration_alumni_recommendations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="buddy",
            field=models.CharField(default="Your Default Value", max_length=255),
        ),
    ]
