# Generated by Django 4.2.2 on 2023-06-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0003_registration_buddy"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="preferences",
            field=models.CharField(
                choices=[
                    ("No preference", "No preference"),
                    (
                        "Final year undergraduate students",
                        "Final year undergraduate students",
                    ),
                    ("Other undergraduate students", "Other undergraduate students"),
                    ("M.Tech students", "M.Tech students"),
                    ("PhD students", "PhD students"),
                ],
                default="No preference",
                max_length=255,
            ),
        ),
    ]
