# Generated by Django 4.2.2 on 2023-06-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0004_registration_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="pref",
            field=models.CharField(
                choices=[
                    ("analytics", "Analytics"),
                    ("civil_services", "Civil Services/Govt. of India"),
                    ("core_engineering", "Core engineering"),
                    ("design", "Design"),
                    ("finance", "Finance"),
                    ("it", "IT"),
                    ("management", "Management"),
                    ("management_consulting", "Management consulting"),
                    ("marketing", "Marketing"),
                    ("other", "Other"),
                    ("product_management", "Product Management"),
                    ("research", "Research"),
                    ("strategy_consulting", "Strategy consulting"),
                ],
                default="default_value",
                max_length=255,
            ),
        ),
    ]
