# Generated by Django 4.2.2 on 2023-06-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0005_alter_registration_pref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="fullname",
            field=models.CharField(max_length=255),
        ),
    ]
