# Generated by Django 4.2.2 on 2023-06-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0006_alter_registration_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="department",
            field=models.CharField(
                choices=[
                    ("aero", "Aerospace Engineering"),
                    ("cse", "Computer Science Engineering"),
                    ("ee", "Electrical Engineering"),
                    ("mech", "Mechanical Engineering"),
                    ("chem", "Chemistry"),
                    ("biosci", "Biosciences & Bioengineering"),
                    ("che", "Chemical Engineering"),
                    ("ieor", "Industrial Engineering and Operations Research"),
                    ("metallurgy", "Metallurgical Engineering and Material Science"),
                    ("engphy", "Engineering Physics"),
                    ("envsci", "Environmental Science & Engineering"),
                    ("energy", "Energy Science & Engineering"),
                    ("math", "Mathematics"),
                    ("civil", "Civil Engineering"),
                    ("earthsci", "Earth Sciences and Resource engineering"),
                    ("rural", "Technology for Rural Areas"),
                    ("design", "Design"),
                    ("other", "Other (If not mentioned above)"),
                ],
                default="default_value",
                max_length=255,
            ),
        ),
    ]
