# Generated by Django 4.2.2 on 2023-06-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0007_alter_registration_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="suggestions",
        ),
    ]
