# Generated by Django 4.2.2 on 2023-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0009_alter_registration_dept_mentees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="registration",
            name="preferences",
        ),
        migrations.AddField(
            model_name="registration",
            name="preferences",
            field=models.ManyToManyField(
                choices=[
                    ("no_preference", "No preference"),
                    ("final_year_undergrad", "Final year undergraduate students"),
                    ("other_undergrad", "Other undergraduate students"),
                    ("mtech_students", "M.Tech students"),
                    ("phd_students", "PhD students"),
                ],
                default="No preference",
                to="asmp_reg.preference",
            ),
        ),
    ]
