# Generated by Django 4.2.2 on 2023-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0010_preference_remove_registration_preferences_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="preferences",
        ),
        migrations.AddField(
            model_name="registration",
            name="preference_final_year_undergrad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="preference_mtech_students",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="preference_no_preference",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="preference_other_undergrad",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="preference_phd_students",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Preference",
        ),
    ]
