# Generated by Django 4.2.2 on 2023-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0011_remove_registration_preferences_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="field_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
