# Generated by Django 4.2.2 on 2023-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmp_reg", "0012_registration_field_other"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="dept_mentees",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
