# Generated by Django 4.2.2 on 2023-06-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asmp_reg",
            "0015_remove_registration_dept_mentees_delete_department_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="hostel",
            field=models.CharField(
                choices=[
                    ("hostel_1", "Hostel 1"),
                    ("hostel_2", "Hostel 2"),
                    ("hostel_3", "Hostel 3"),
                    ("hostel_4", "Hostel 4"),
                    ("hostel_5", "Hostel 5"),
                    ("hostel_6", "Hostel 6"),
                    ("hostel_7", "Hostel 7"),
                    ("hostel_8", "Hostel 8"),
                    ("hostel_9", "Hostel 9"),
                    ("hostel_10", "Hostel 10"),
                    ("hostel_11", "Hostel 11"),
                    ("hostel_12", "Hostel 12"),
                    ("hostel_13", "Hostel 13"),
                    ("hostel_14", "Hostel 14"),
                    ("hostel_15", "Hostel 15"),
                    ("tansa", "Tansa"),
                    ("qip", "QIP"),
                ],
                default="default_value",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="pref",
            field=models.CharField(
                choices=[
                    ("analytics", "Analytics"),
                    ("civil_services", "Civil Services/Govt. of India"),
                    ("core_engineering", "Core engineering"),
                    ("design", "Design"),
                    ("finance", "Finance"),
                    ("it", "IT"),
                    ("management", "Management"),
                    ("management_consulting", "Management consulting"),
                    ("marketing", "Marketing"),
                    ("product_management", "Product Management"),
                    ("research", "Research"),
                    ("strategy_consulting", "Strategy consulting"),
                    ("entrepreneurship", "Entrepreneurship"),
                    ("other", "Other"),
                ],
                default="default_value",
                max_length=255,
            ),
        ),
    ]
